[options]
; Database
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo

; Addons
addons_path = /root/workspace/kebun/odoo-19.0+e.20260709/odoo/addons,/root/workspace/kebun/odoo-data/addons/19.0

; HTTP
http_port = 8069
http_interface = 0.0.0.0

; Log
log_level = info
logfile = /root/workspace/kebun/odoo.log

; Data
data_dir = /root/workspace/kebun/odoo-data

; Dev mode
dev_mode = all

; Enterprise subscription code
subscription_code = M20071317488743
